### ISSUE TITLE
科普帖

### ISSUE THREAD

**Issue by Memorablea** [Memorablea/COVID-19-#11]
- 汇总自拍帮主微博的持续感染标记突变

 S:H245Y、 S:K440R、 S:V486F、ORF1a:L3829F、S:H519R 、S:S1003I、ORF1b:G662S

https://weibo.com/7789369753/Mv4VWoPap
https://weibo.com/7789369753/MCPRxdN0V

**Comment by Memorablea** [comment]
关闭他

**Comment by Outpfmance** [comment]
天阶理论/最高阶数：
R346S/T
K356T
R403S/K
N405K
N417Krev/K417Y
N439K
K440Nrev/N440E/Q/T
K444N/E
V445D/A/S/H/R/L
G446D/S
N450K/D
L452R/M/Q
Y453F/C
L455F/W/S
F456L/C/V
N460K/H/I/S/T
T478R/N
F486P/S/V
F490L/P/S/V
R493Qrev
S494P
N505Yrev/Y505D
