### ISSUE TITLE
中国大陆地区流行的值得关注的变体

### ISSUE THREAD

**Issue by Outpfmance** [Memorablea/COVID-19-#13]
[Currently circulating variants of interest in China.xlsx](https://github.com/Memorablea/Memorable/files/11301672/Currently.circulating.variants.of.interest.in.China.xlsx)

**Comment by Memorablea** [comment]
> [Currently circulating variants of interest in China.xlsx](https://github.com/Memorablea/Memorable/files/11301672/Currently.circulating.variants.of.interest.in.China.xlsx)

文字版：中国大陆地区VOC为BA.5.2.48及其子系、BF.7.14及其子系和XBB.1.9.1。VOL为XBB.1.5及其子系、BA.5.2.49及其子系和XBB.1.16及其子系。另外，VUM为XBB.1.19.1 XBB.1.9.2 BF.7 BA.5.2 XBB.1.22.1 BN.1及其子系

**Comment by Outpfmance** [comment]
[Currently circulating variants of interest in China.xlsx](https://github.com/Memorablea/Memorable/files/11363926/Currently.circulating.variants.of.interest.in.China.xlsx)

**Comment by Memorablea** [comment]
> > [目前在中国流行的感兴趣的变体.xlsx](https://github.com/Memorablea/Memorable/files/11301672/Currently.circulating.variants.of.interest.in.China.xlsx)
> 
> 文字版：中国大陆地区VOC为BA.5.2.48及其子系、BF.7.14及其子系和XBB.1.9.1。VOI为XBB.1.5及其子系、BA.5.2.49及其子系和XBB.1.16及其子系。另外，VUM为XBB.1.19.1 XBB.1.9.2 BF.7 BA.5.2 XBB.1.22.1 BN.1及其子系

最新更新版：XBB.1.5升级为VOC，XBB.1.22.1升级为VOI，将BQ.1.1.13加入VUM

**Comment by Memorablea** [comment]
XBB.1.22.1（VOI）带有ORF1a:E750K的子系刚刚被指定为XBB.1.22.1.3（FY.3）
![image](https://user-images.githubusercontent.com/125779492/236476309-93ea940a-ddff-4f55-b621-173c6cc77a7e.png)

**Comment by Outpfmance** [comment]
由于中国疾控中心自4月29号之后不再发布周报等有关信息，我将改组这个项目，在这期间，我将关闭它直至改组完成
