### ISSUE TITLE
中国XBB*统一期

### ISSUE THREAD

**Issue by Outpfmance** [Memorablea/COVID-19-#17]
![IMG_0176](https://user-images.githubusercontent.com/125484893/236672971-285b7761-67e9-4215-9d6e-880d05974e6a.jpeg)

4月29号，广东上传大量GISAID序列

**Comment by Outpfmance** [comment]
![IMG_0246](https://user-images.githubusercontent.com/125484893/236673064-330cfaa9-175b-434f-8cca-de3a2c0df3fe.jpeg)

5月5号-5月6号，上海等城市上传GISAID
可以看到，XBB*已经取代了BA.5*

**Comment by Memorablea** [comment]
近期，非XBB*血统即将全部清零，重新打开它！

**Comment by Memorablea** [comment]
根据采样日期，XBB及其亚分支的占比逐渐增加，从2023年第27周（7月3日-7月9日）的96.3%，增长到第30周（7月24日-7月30日）的99.1%。见图。 
![image](https://github.com/Memorablea/COVID-19-/assets/125779492/26e07887-5a26-4d37-8a8f-e515b1ef1a9f)
