### ISSUE TITLE
Lineage Special tracking （Thx @FedeGueli

### ISSUE THREAD

**Issue by Memorablea** [Memorablea/COVID-19-#22]
专项追踪

- [ ] 各个分支的跃迁演化
- [ ] FL.2.3.1 + S:Q14R `A21603G, G29543T`
- [ ] EG.5.1.1 with S:P681R
- [ ] S：403K
- 等待更新......

**Comment by Memorablea** [comment]
XBB.1.16带有S：V551I
最早：2023-04-05
最近：2023-04-19
（请注意，我指的时间为上报时间，故仍然应进行监控）
分布：上海、印度
序列：EPI ISL 17591908、EPI ISL 17530314、EPI ISL 17536936、EPI ISL_17511858、EPI ISL_17619227、EPI ISL_17618926
![image](https://user-images.githubusercontent.com/125779492/237010738-a75cf9c9-15ea-441c-b0ea-8ff075c5acc3.png)
![image](https://user-images.githubusercontent.com/125779492/237011532-ba9dbb97-3eb8-4977-a804-d70e11cfb95d.png)

XBB.1.16 with S: V551I
Earliest: April 5th, 2023
Recently: April 19, 2023
(Please note that the time I am referring to is the reporting time, so monitoring should still be carried out)
Distribution: Shanghai, India
sequence：EPI ISL 17591908、EPI ISL 17530314、EPI ISL 17536936、EPI ISL_17511858、EPI ISL_17619227、EPI ISL_17618926
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_30876_9e30b0.json?label=id:node_3155738
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_30876_9e30b0.json

**Comment by Memorablea** [comment]
T10810C FY.3 19 sequences
![image](https://github.com/Memorablea/COVID-19-/assets/125779492/345bde9d-c713-4ad0-9d71-d33d083bbb3b)

**Comment by Memorablea** [comment]
>我建议对中国的XBB.1.22.1进行指定

经过观察，我已经在Pango Issues发布FY.3和A11556G的内容，希望这条可以对将要进行指定的人有帮助

**Comment by Outpfmance** [comment]
![IMG_0392](https://github.com/Memorablea/COVID-19-/assets/125484893/ad20bf31-55d3-458e-8a86-82c53b6b06ab)
这也是一个还在增长的中国本土跃迁分支，为BA.2.75*系的BN.1*的分支

**Comment by Memorablea** [comment]
关闭，等待有必要的更新

**Comment by Memorablea** [comment]
EPI_ISL_17703983疑似为XBB.1.19和XBB.1.22的重组

**Comment by FedeGueli** [comment]
Thx @Memorablea and @over_There_is  i have proposed it : https://github.com/sars-cov-2-variants/lineage-proposals/issues/196

**Comment by Memorablea** [comment]
> Sorry i ve missed that this was the right place to discuss. i hev deleted msg in # 25

Thank you for understanding!

**Comment by Memorablea** [comment]
Thank you @FedeGueli , this item has been changed to a dedicated tracking.

**Comment by FedeGueli** [comment]
Thank you very much @Memorablea !

**Comment by Memorablea** [comment]
@FedeGueli 这里发现了几个，不太了解是否重复
![image](https://github.com/Memorablea/COVID-19-/assets/125779492/bfdb9288-5805-4432-89cd-c7a44e4c4f6d)

**Comment by Memorablea** [comment]
> 专项追踪
> * 等待更新......

上海的FU.1大量更新，仅6月16日一天上报123例。

**Comment by Walde1nsamkeit** [comment]
上海DY.2跃迁突变 涉及14碱基和10氨基酸变化

Shanghai/SCDC-XG06-7545/2023|EPI_ISL_17811279|2023-05-28

DY.2> T9160A> C745T, C6936T(Orf1a:**S2224F**), G8264A(Orf1a:**G2667S**), C12763T, G13385A(Orf1a:**G4374S**), C20404T(Orf1b:**P2313S**), G22200A(S:**G213E**), C22295T(S:**H245Y**), G23018Trev(S:**V486F**rev), G24368C(S:**D936H**), C26408T(E:**S55F**), C28512G(N:**P80R**), A28795G, C29149T

带有长期感染标志突变S:H245Y, V486Frev

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/SH-XG2306-7545/2023"
                     /isolation_source="Nasopharyngeal swab"
                     /host="Homo sapiens; Host_age: 71; Host_sex: Male"
                     /country="China:Shanghai"
                     /collection_date="2023-05-28"
                     /note="Passage_details/history: Original"

**Comment by Walde1nsamkeit** [comment]
河南驻马店BF.7.14跃迁突变 涉及16碱基和4氨基酸变化

Henan/ZMDCDC-131/2023|EPI_ISL_17817003|2023-04-27

BF.7.14> G28376A(N:A35T)
\> C7093T, T7453C, C11962A, G14126A(Orf1b:S220N), T24763C, C26276T(E:T11M)
\> C19269T, T28251G(Orf8:F120V), A28254C(Orf8:I121L)
\> A812G(Orf1a:**T183A**), C3787T, C9073T, C10798T, C10868T, C11747T, C11750T(Orf1a:**L3829F**), C12789T(Orf1a:**T4175I**), T13644C, C17745T, A18600G, C20629T(Orf1b:H2388Y), C21727T, G22200Trev(S:**G213V**rev), C29679T, C29732T

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/ZMDCDC-131/2023"
                     /isolation_source="Oro-pharyngeal swab"
                     /host="Homo sapiens; Host_age: 16; Host_sex: female"
                     /country="China:Henan,Zhumadian"
                     /collection_date="2023-04-27"
                     /note="Passage_details/history: Original"

![2023-06-20 (10)](https://github.com/Memorablea/COVID-19-/assets/38100637/ea8ed79f-a61a-4e4c-8c3d-ace054985336)

**Comment by Walde1nsamkeit** [comment]
云南DY.1跃迁
Yunnan/YNCDC-1366/2023|EPI_ISL_17830456|2023-06-03
DY.1> C12970T
\> C27707T(Orf7a:A105V)
\> C3902T(Orf1a:P1213S), C5314T, C6573T(Orf1a:S2103F), C6681T(Orf1a:A2139V), C7874T(Orf1a:P2537S), C17130T
\> C1479T(Orf1a:**A405V**), C3157T, C3653T(Orf1a:**L1130F**), T12136C, C13197T(Orf1a:**T4311I**), C13501T(Orf1b:**P12S**), G15451A(Orf1b:**G662S**), C23315T(S:**L585F**), A26709Grev(M:**T63A**rev), T27522A(Orf7a:**N43K**), G28027A(Orf8:**W45\***), G28134A(Orf8:~V81I~), C29098T, C29627T(Orf10:**R24C**)

                     /organism="Severe acute respiratory syndrome coronavirus 2"
                     /mol_type="genomic RNA"
                     /isolate="SARS-CoV-2/human/CHN/YNCDC-1366/2023"
                     /isolation_source="Oro-pharyngeal swab"
                     /host="Homo sapiens; Host_age: 69; Host_sex: Male"
                     /country="China:Yunnan"
                     /collection_date="2023-06-03"
![2023-06-22 (9)](https://github.com/Memorablea/COVID-19-/assets/38100637/1c107a9b-507e-4978-9908-63d1c44b916f)

**Comment by Memorablea** [comment]
> 专项追踪
> * XBB.1.9.1 + Orf1a：L3588F （NSP6_L19F）

There are currently 72 sequences from 6 countries.

**Comment by Memorablea** [comment]
FU.1+A460G 116条
![image](https://github.com/Memorablea/COVID-19-/assets/125779492/18c4db50-66c6-4cb6-9115-cd4804c1a20b)

**Comment by Walde1nsamkeit** [comment]
新疆阿克苏BA.5.2.48跃迁 两条位于同一分支，均带V486Frev
![2023-06-26 (5)](https://github.com/Memorablea/COVID-19-/assets/38100637/30657cb9-4afb-4f5b-acd0-af6ddf5800aa)

**Comment by FedeGueli** [comment]
Hi i would like to highlight this FL.2.3 with S:K356T likely emerged in China:
![Schermata 2023-07-01 alle 18 25 56](https://github.com/Memorablea/COVID-19-/assets/87669813/163d0b12-dfb7-4d29-b60b-566b35a0d16a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_53fb_3c360.json?label=id:node_10475998

**Comment by FedeGueli** [comment]
And also this FU.1 sequence with S:N354K https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_5aee_3c8a0.json 
![Schermata 2023-07-01 alle 18 28 16](https://github.com/Memorablea/COVID-19-/assets/87669813/92b1a9ad-effb-4068-940b-907ade5da0f6)

Very recent . In the past there has been one quite successful BA.4  (i think BA.4.10) with S:N354D so maybe worth keeping tracked

**Comment by Walde1nsamkeit** [comment]
Shanxi/TYCDC-096/2023|EPI_ISL_17951387|2023-04-21
BF.7.14.5>T27532Crev(Orf7a:Y47Hrev)
\>C13883T(Orf1b:T139I)
\>C2509T, T4930C, C10228T
\>G704A(Orf1a:**D147N**), C1404A(Orf1a:**P380H**), A2380G, A3342G(Orf1a:**N1026S**), A3647G(Orf1a:**I1128V**), A3829C, C12623T(Orf1a:**P4120S**), T12862C, C27999T(Orf8:**P36S**), A28482G(N:**Q70R**)

**Comment by FedeGueli** [comment]
I suggest very much to add this to the tracking list, in my math its doubling time is short. https://github.com/sars-cov-2-variants/lineage-proposals/issues/191

**Comment by Memorablea** [comment]
> I suggest very much to add this to the tracking list, in my math its doubling time is short. [sars-cov-2-variants/lineage-proposals#191](https://github.com/sars-cov-2-variants/lineage-proposals/issues/191)

Understand

**Comment by Memorablea** [comment]
#196 and #117 @Over-There-Is continues to track the issue interface, and I mark it as complete. Thank you @FedeGueli .

**Comment by FedeGueli** [comment]
Just  a singlet but worrisome from Singapore an EG.5.1.1 with S:K356T it clusters with samples from Shanghai early in June while this has been collected on 26th of June in Singapore: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_33e08_5c8800.json?c=gt-ORF1ab_2092 this may point to an ongoing circualtion in Shanghai (or maybe not , cause there already more than 100 seqs from Shanghai after June 20th and none of this lineage)

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_4a392_651b30.json?c=userOrOld&label=id:node_10505271 singlet from Shanghai with S:V70A , S:F490P (reached with a trilple nuc mutation) and a large del between 139-146

**Comment by Memorablea** [comment]
OK

**Comment by Walde1nsamkeit** [comment]
国内流通的XBB.1.5.15以G1820A(Orf1a:G519S)分支为主，但没有FD.2定义中的C21998A(S:Q146K)
`G15957T, G1820A, -C21998A`可以搜索到112条序列
而`G15957T, G1820A, C21998A`仅能搜索到新疆博尔塔拉蒙古族自治州的两条序列
与国外的XBB.1.5.15+G1820A少、FD.2多完全相反
其他株系常常出现Q146K变异，不大可能出现反向的K146Q测序错误(?)
数量差异足够悬殊，基本可排除测序错误的原因
该支系是否FD.2的邻近支系？

**Comment by Walde1nsamkeit** [comment]
#369 现流通于新西兰 疑似国产

**Comment by Memorablea** [comment]
由 @Outpfmance 发现：湖北省一条EG.5.1(.1)带有S:P681R

**Comment by Walde1nsamkeit** [comment]
Ukraine/80095/2023|EPI_ISL_18131053|2023-07-27 Dnipropetrovsk Oblast, Ukraine
This singlet has been uploaded for days, but it's too hard to analyze. I am also not sure if this sequence really a recombinant. It has feature of both BA.1 and BA.2, but it has too many breakpoints, seems the sample is contaminated. But it also nearly impossible to find two chronic infectors at the same time and collect their sample.
Somebody said it is possible for a chronic co-infection to lead to recombine multiple times and forms multiple breakpoints, but I forgot who he is. Nekromanzer? Outpfmance? Or Paibangzhu[potential another identity of Sakaguchi]?
And I forgot where I saw that BA.1 has ins214EPE and remembered this sequence, I did not notice this ever.
This sequence seems gained lots of mutations through saltation, including some convergent mutations nowadays. It seems this singlet is not spreading yet, but Ukraine has not uploaded sequence for half a month.

BA.1.1 / BA.2+C9866T
Mutations based on the common ancestor of BA.1/2: 
C44T, T670G, A761G, C2455T, C2790T, G4184A, C4321T, C5183T, A6505G, G7553A, C8016T, G8393A, C8626T, C9042T, G9753A, C9866T, C10198T, G10447A, C10507T, C12400T, C12880T, T13195C, G13459T, A14226G, C15240T, C17676T, A19443G, A20055G, C20930T, C21588T, C21762T, 21765..21770 (6 bp), C21846T, 21987..21995 (9 bp), G22132T, 22194..22196 (3 bp), ins22204GAGCCAGAA, C22212T, G22599A, A22688G, G22775A, A22786C, A22812C, A22881G, T22896C, A22941C, C22971A, T22977C, T23030G, G23040A, G23222A, C23230T, C23453T, A23534G, C24130A, G24368T, C24503T, A25326G, G25681A, C26060T, C26600T, T26494G, T26551C, C26728T, A26739G, C26858T, A27403G, T27837G, A29510C,	29734..29759 (26 bp)

Breakpoint 1: BA.2 6515\~8393 BA.1.1
Breakpoint 2: BA.1.1 9534\~9866 BA.2
Breakpoint 3: BA.2 12880\~13195 BA.1.1
Breakpoint 4: BA.1.1 19955\~20055 BA.2
Breakpoint 5: BA.2 20055\~21618 BA.1.1
Breakpoint 6: BA.1.1 22599\~22673 BA.2
Breakpoint 7: BA.2 23202\~24130 BA.1.1
Breakpoint 8: BA.1.1 24503\~26060 BA.2
This sequence does not have G27382C, A27383T, T27384C, there are potentially 2 more breakpoint: 26858\~27382 and 27382\~29510.
Extra Mutations: A761G, C2455T, C5183T, A6505G, G7553A, C8016T, C8626T, C9042T, G9753A, **C9866T(Main branch of BA.2)**, C10507T, C12400T, G13459T, A14226G, C17676T, A19443G, C20930T, C21588T, G22132T, C22212T, **G22599A(BA.1.1)**, A22812C, A22881G, T22896C, A22941C, C22971A, T22977C, T23030G, G23040A, G23222A, C23230T, C23453T, A23534G, G24368T, A25326G, G25681A, C26600T, T26494G, T26551C, C26728T, A26739G, A27403G, T27837G

**Comment by ryhisner** [comment]
There were a number of extremely divergent and unusual sequences uploaded from Ukraine a few weeks ago. They were all uploaded by the "Reference laboratory for diagnostics of HIV/AIDS", so I think there can be little doubt these sequences came from individuals with HIV who have been chronically infected for a very long time, possibly complicated by coinfection with multiple variants and an untold amount of intrahost recombination.

**Comment by Walde1nsamkeit** [comment]
Yunnan/YNCDC-2534/2023|EPI_ISL_18241470|2023-08-16 FL.21.2+F456L
Yunnan/YNCDC-2428/2023|EPI_ISL_18241448|2023-08-12 FL.21.2+Q14R

**Comment by Walde1nsamkeit** [comment]
FL.2.3> N:R189L> S:N354K 9seq

**Comment by Walde1nsamkeit** [comment]
FL.4.2+Q14H+P521S+A701V Heilongjiang/HLJCDC-2138/2023|EPI_ISL_18246167|2023-08-14
FL.4.2+K356T Heilongjiang/HLJCDC-2092/2023|EPI_ISL_18246080|2023-08-08
FL.4.2+F157L Heilongjiang/HLJCDC-1861/2023|EPI_ISL_18246168|2023-07-11

**Comment by Walde1nsamkeit** [comment]
Shanghai/SCDC-XG09-13173/2023|EPI_ISL_18268466|2023-08-24 FL.2.3.1+K478R+T523I
Shanghai/SCDC-XG09-12958/2023|EPI_ISL_18268444|2023-08-28 FL.2.3.1+Q14L

**Comment by Walde1nsamkeit** [comment]
Hubei/HCDC-YC2844/2023|EPI_ISL_18268174|2023-08-23 FL.4(on N:K256R branch)+F456L+S494P+S691P

**Comment by Walde1nsamkeit** [comment]
Fujian/FCDC-LY1864/2023|EPI_ISL_18277141|2023-09-11 EG.5.1.1> C26681T> T5327C, C5986T, T22032C(S:F157S), G22927T(S:L455F)

**Comment by Walde1nsamkeit** [comment]
Sichuan/MYCDC-XGCX323/2023|EPI_ISL_18284777|2023-08-30 FE.1.1.3 saltation K356T, R403K, Y453F, S490P, K537E, A688V, K1045R

**Comment by Walde1nsamkeit** [comment]
Japan/PG-564972/2023|EPI_ISL_18285429|2023-08-30 FL.2.3+S939F

**Comment by FedeGueli** [comment]
> Sichuan/MYCDC-XGCX323/2023|EPI_ISL_18284777|2023-08-30 FE.1.1.3 saltation K356T, R403K, Y453F, S490P, K537E, A688V, K1045R

please propose it very bad looking. URGENT.

**Comment by FedeGueli** [comment]
> Fujian/FCDC-LY1864/2023|EPI_ISL_18277141|2023-09-11 EG.5.1.1> C26681T> T5327C, C5986T, T22032C(S:F157S), G22927T(S:L455F)

Please post on # 537

**Comment by Walde1nsamkeit** [comment]
> > Fujian/FCDC-LY1864/2023|EPI_ISL_18277141|2023-09-11 EG.5.1.1> C26681T> T5327C, C5986T, T22032C(S:F157S), G22927T(S:L455F)
> 
> Please post on # 537

Already included by Nekromanzer.

**Comment by Walde1nsamkeit** [comment]
Anhui/AQCDC-147/2023|EPI_ISL_18289781|2023-08-27 FL.2.3.1+S490P

**Comment by Walde1nsamkeit** [comment]
Anhui/AQCDC-133/2023|EPI_ISL_18289787|2023-08-20 FE.1.1+F157L
Anhui/HFCDC-681/2023|EPI_ISL_18289827|2023-08 FU.1+Q14R
Anhui/HFCDC-712/2023|EPI_ISL_18289858|2023-09 FU.1+Q14R
Anhui/HCDC-150/2023|EPI_ISL_18289746|2023-08-14 FY.3.1+F157L
Anhui/HFCDC-733/2023|EPI_ISL_18289879|2023-09 FY.3.3+G181A, F456L(already 2 seq)
Henan/XYCDC-0271/2023|EPI_ISL_18289917|2023-08-03 FL.4+F456L

**Comment by FedeGueli** [comment]
That FY.3.3 if reaches 5 it is worth a proposal

**Comment by Walde1nsamkeit** [comment]
Yunnan/YNCDC-2608/2023|EPI_ISL_18292741|2023-08-24
Yunnan/YNCDC-2610/2023|EPI_ISL_18292743|2023-08-27
XBB.1.16+L455F

**Comment by Walde1nsamkeit** [comment]
Yunnan/YNCDC-2716/2023|EPI_ISL_18292849|2023-09-05 FL.15+W152R, F186S
Yunnan/YNCDC-2585/2023|EPI_ISL_18292718|2023-08-28 FL.15+Q14H

**Comment by FedeGueli** [comment]
I have contacted you both on twitter please check dms

**Comment by Walde1nsamkeit** [comment]
> Japan/PG-564972/2023|EPI_ISL_18285429|2023-08-30 FL.2.3+S939F

Japan/PG-569108/2023|EPI_ISL_18294163|2023-08-29

**Comment by Walde1nsamkeit** [comment]
Henan/JZCDC-141/2023|EPI_ISL_18300570|2023-07-18 FL.4+F456L, T961M
(Henan/JZCDC-134/2023|EPI_ISL_18213329|2023-07-15)

**Comment by Walde1nsamkeit** [comment]
Qinghai/QHCDC-HSZ-400/2023|EPI_ISL_18268266|2023-09-11
Orf8:M1L(Destroying the initiation codon)

**Comment by Walde1nsamkeit** [comment]
> Qinghai/QHCDC-HSZ-400/2023|EPI_ISL_18268266|2023-09-11 Orf8:M1L(Destroying the initiation codon)

Hong_Kong/VB23163707/2023|EPI_ISL_18306770|2023-09-11

**Comment by FedeGueli** [comment]
This orf8 could be interesting to propose to keep track of orf8 variability

**Comment by Walde1nsamkeit** [comment]
Hong_Kong/VB23156956/2023|EPI_ISL_18306763|2023-08-31 EG.5.1.1+K356T
Sichuan/NJCDC-0921-6/2023|EPI_ISL_18304261|2023-09-17 EG.5.1.1+L455F+A484V

**Comment by Walde1nsamkeit** [comment]
Yunnan/YNCDC-2840/2023|EPI_ISL_18324168|2023-09-07
BA.2.75.2 Saltation?
I19Trev, R190S, T240P, S446N, L452Q, V483F, P621T, I1172V
Maybe related to Myanmar?

**Comment by FedeGueli** [comment]
> Yunnan/YNCDC-2840/2023|EPI_ISL_18324168|2023-09-07 BA.2.75.2 Saltation? I19Trev, R190S, T240P, S446N, L452Q, V483F, P621T, I1172V Maybe related to Myanmar?

Worth proposing to highlight it. Thank you

**Comment by Memorablea** [comment]
> > Yunnan/YNCDC-2840/2023|EPI_ISL_18324168|2023-09-07 BA.2.75.2 Saltation? I19Trev, R190S, T240P, S446N, L452Q, V483F, P621T, I1172V Maybe related to Myanmar?
> 
> Worth proposing to highlight it. Thank you

@Over-There-Is 提出它

**Comment by Walde1nsamkeit** [comment]
> > > Yunnan/YNCDC-2840/2023|EPI_ISL_18324168|2023-09-07 BA.2.75.2 Saltation? I19Trev, R190S, T240P, S446N, L452Q, V483F, P621T, I1172V Maybe related to Myanmar?
> > 
> > 
> > Worth proposing to highlight it. Thank you
> 
> @Over-There-Is 提出它

Stop your machine translation

**Comment by Walde1nsamkeit** [comment]
FY.3 Saltation
FY.3> T10810C> T19680C> C3784T, C6501T(Orf1a:P2079L), C12854T(Orf1a:P4197S), C13335T(Orf1a:A4357V), A17737T(Orf1b:T1424S), C20132T(Orf1b:A2222V), C22498T, T22555C, G24914T(S:D1118Y), G28871A(N:G200S), C29762T
4 seq Xiaogan, Hubei, China 09-08~09-13
Credit to @NkRMnZr

**Comment by FedeGueli** [comment]
/

> FY.3 Saltation FY.3> T10810C> T19680C> C3784T, C6501T, C12854T, C13335T, A17737T, C20132T, C22498T, T22555C, G24914T, G28871A, C29762T 4 seq Xiaogan, Hubei, China 09-08~09-13 Credit to @NkRMnZr

All silent??

**Comment by Walde1nsamkeit** [comment]
> /
> 
> > FY.3 Saltation FY.3> T10810C> T19680C> C3784T, C6501T, C12854T, C13335T, A17737T, C20132T, C22498T, T22555C, G24914T, G28871A, C29762T 4 seq Xiaogan, Hubei, China 09-08~09-13 Credit to @NkRMnZr
> 
> All silent??

Added now.

**Comment by FedeGueli** [comment]
XCN showed up in Gansu , recent sample EPI_ISL_18401744 6th october.

**Comment by Walde1nsamkeit** [comment]
Hong_Kong/VB23182287/2023|EPI_ISL_18412334|2023-10-01
EG.5.1.1+I68T, T549I, V635I, E1144V

**Comment by Walde1nsamkeit** [comment]
FE.1.1.1+Orf9b:I5T 65 seq mainly in US T9445C, C28093T, T28297C

**Comment by Walde1nsamkeit** [comment]
FL.2.3.1+Q14R 2 seq T1270C, T3883C, A21603G
China 1(Heilongjiang), Switzerland 1(Ticino)  EPI_ISL_18384445 EPI_ISL_18397929

**Comment by Walde1nsamkeit** [comment]
Anhui\/TLCDC-CX040\/2023|EPI_ISL_18409183|2023-07-31 FL.2.3.1+S704L

**Comment by FedeGueli** [comment]
> T9445C, C28093T, T28297C

very slow one.

**Comment by Walde1nsamkeit** [comment]
Mexico/VER_InDRE_FB4196/2023|EPI_ISL_18424291|2023-08-19 FL.21.2+S:E554Q

**Comment by Walde1nsamkeit** [comment]
T19776C, C21707T, G22037A
FL.2.3.1+Y49H, V159I, P812S
Alberta, Canada 4 seq

**Comment by Walde1nsamkeit** [comment]
South_Korea/KDCA268339/2023|EPI_ISL_18435652|2023-10-01 FL.2.3+Q14H, A653V

**Comment by Walde1nsamkeit** [comment]
Canada\/MB-CPL-653580\/2023|EPI_ISL_18429933|2023-09-26 GW.1+C6525T(T2087I, Definition of JN.3)

**Comment by Walde1nsamkeit** [comment]
Beijing/BJCDC-2781/2023|EPI_ISL_18438180|2023-06-04 GW.1.1+G184S
Beijing 06-04
Seems stopped growing

**Comment by Walde1nsamkeit** [comment]
Beijing/BJCDC-4318/2023|EPI_ISL_18438229|2023-08-31 XBB.1.42.2+Q14H, A626V

**Comment by Walde1nsamkeit** [comment]
FL.1.5.1> C26894T> C25931T(Orf3a:S180F)> A17615G(Orf1a:K1383R) 6seq, US

**Comment by Walde1nsamkeit** [comment]
> FL.2.3.1+Q14R 2 seq T1270C, T3883C, A21603G China 1(Heilongjiang), Switzerland 1(Ticino) EPI_ISL_18384445 EPI_ISL_18397929

5 seq now, China 4:Heilongjiang 3, Xinjiang 1(Urumqi); Switzerland 1(Ticino)
Heilongjiang/HLJCDC-2366/2023|EPI_ISL_18465045|2023-09-19 E309Q(2 seq)
Heilongjiang/HLJCDC-2456/2023|EPI_ISL_18465139|2023-10-05 A484S

**Comment by Walde1nsamkeit** [comment]
Shanghai/SCDC-XG10-14604/2023|EPI_ISL_18465384|2023-09-30 under FL.2.3>N:R189L>S:F456L branch
Q14R, L455F

**Comment by Walde1nsamkeit** [comment]
EG.5.1.8+Orf1a:L3829F 2seq

**Comment by FedeGueli** [comment]
> Shanghai/SCDC-XG10-14604/2023|EPI_ISL_18465384|2023-09-30 under FL.2.3>N:R189L>S:F456L branch Q14R, L455F

please propose this one if it turns 2

**Comment by Walde1nsamkeit** [comment]
Hong_Kong/VB23204967/2023|EPI_ISL_18466251|2023-10-27
FQ.1> T6571C> C26537T> T378C(Orf1a:V38A), C503T(Orf1a:P80S), C629T(Orf1a:L122F), T1354C, A1818G(Orf1a:K518R), C2721T(Orf1a:A819V), G2897A(Orf1a:A878T), C3619T, A4233G(Orf1a:D1323G), C5178A(Orf1a:T1638N), A5227G, C7644T(Orf1a:A2460V), A7986T(Orf1a:Q2574L), C9073T, G9383T(Orf1a:A3040S), C10279T, A12762G(Orf1a:D4166G), C17626T(Orf1b:H1387Y), C17733T, G18340A(Orf1b:V1625I), G19282A(Orf1b:D1939N), G19480A(Orf1b:G2005S), C19524T, T22729C, G23429A(S:A623T), C23763T(S:T734I), C26198T(Orf3a:T269M), G27087A(M:G189S), C27208T(Orf6:H3Y), T27504C, T27780C(Orf7b:F9L), T27889Crev, del28254(Orf8:I121fs), C28957T, A29700G
34 sub and 1 del(frameshift) saltation

**Comment by Walde1nsamkeit** [comment]
Shanghai/SCDC-XH1020-48_S48/2023|EPI_ISL_18475201|2023-10-13 FL.21.2+K356T, S704L

**Comment by Walde1nsamkeit** [comment]
HCDC-SY3488/2023|EPI_ISL_18485310|2023-10-24 FL.15.2>L455F>D215N, A845V

**Comment by Walde1nsamkeit** [comment]
Fujian/FCDC-QZ11S001/2023|EPI_ISL_18495156|2023-10-25 JH.1+F157L, K478R
                     /note="Passage_details/history: sample collected following
                     travel from Africa; Patient_status: Released"
But not mentioned which country.

Shanxi/TYCDC372/2023|EPI_ISL_18495303|2023-07-18 DY.2+T732I> P9L, R214H, R403S, K444M, V486Frev
Shanxi/TYCDC373/2023|EPI_ISL_18495304|2023-07-18 DY.2+P9L, D215G, K444N, A484V
Shanxi/TYCDC426/2023|EPI_ISL_18495357|2023-08-04 DY.2+T95I, E340K, R403K, K444N, R452Q, N460K, V483A, A484V, N658D
Shanxi/TYCDC485/2023|EPI_ISL_18495416|2023-09-01 BF.7.14+W152L, D339H, V455A, V486Frev, T547K, A570V, P1143S, D1260H
Shanxi/TYCDC445/2023|EPI_ISL_18495376|2023-08-11 BF.7.14.4+Y508H, D936H
Shanxi/TYCDC601/2023|EPI_ISL_18495532|2023-11-03 FL.2.3+Q146K> T20N, D428Y, H505Yrev

**Comment by FedeGueli** [comment]
> Fujian/FCDC-QZ11S001/2023|EPI_ISL_18495156|2023-10-25 JH.1+F157L, K478R /note="Passage_details/history: sample collected following travel from Africa; Patient_status: Released" But not mentioned which country.
> 
> Shanxi/TYCDC372/2023|EPI_ISL_18495303|2023-07-18 DY.2+T732I> P9L, R214H, R403S, K444M, V486Frev Shanxi/TYCDC373/2023|EPI_ISL_18495304|2023-07-18 DY.2+P9L, D215G, K444N, A484V Shanxi/TYCDC426/2023|EPI_ISL_18495357|2023-08-04 DY.2+T95I, E340K, R403K, K444N, R452Q, N460K, V483A, A484V, N658D Shanxi/TYCDC485/2023|EPI_ISL_18495416|2023-09-01 BF.7.14+W152L, D339H, V455A, V486Frev, T547K, A570V, P1143S, D1260H Shanxi/TYCDC445/2023|EPI_ISL_18495376|2023-08-11 BF.7.14.4+Y508H, D936H Shanxi/TYCDC601/2023|EPI_ISL_18495532|2023-11-03 FL.2.3+Q146K> T20N, D428Y, H505Yrev

Thank you JH.1 is  a dark horse in Africa. also the last one seems interesting lets see if 505 rev is real or not.

**Comment by Walde1nsamkeit** [comment]
> > FL.2.3.1+Q14R 2 seq T1270C, T3883C, A21603G China 1(Heilongjiang), Switzerland 1(Ticino) EPI_ISL_18384445 EPI_ISL_18397929
> 
> 5 seq now, China 4:Heilongjiang 3, Xinjiang 1(Urumqi); Switzerland 1(Ticino) Heilongjiang/HLJCDC-2366/2023|EPI_ISL_18465045|2023-09-19 E309Q(2 seq) Heilongjiang/HLJCDC-2456/2023|EPI_ISL_18465139|2023-10-05 A484S

Gansu +1, 6 now, without T1270C and T3883C
New query: A21603G, G29543T

**Comment by FedeGueli** [comment]
> A21603G, G29543T

Thx for the new query
Lets wait for some more recent samples, it is enough one more from , to say, mid october to propose it.

**Comment by Walde1nsamkeit** [comment]
> Shanghai/SCDC-XG10-14604/2023|EPI_ISL_18465384|2023-09-30 under FL.2.3>N:R189L>S:F456L branch Q14R, L455F

No, sars-cov-2-variants/lineage-proposals#1068 is first mentioned here, and proposed on 8 Nov, and quoted by sars-cov-2-variants/lineage-proposals/issues/526 on 11 Nov. @FedeGueli

**Comment by FedeGueli** [comment]
> > Shanghai/SCDC-XG10-14604/2023|EPI_ISL_18465384|2023-09-30 under FL.2.3>N:R189L>S:F456L branch Q14R, L455F
> 
> No, [sars-cov-2-variants/lineage-proposals#1068](https://github.com/sars-cov-2-variants/lineage-proposals/issues/1068) is first mentioned here, and proposed on 8 Nov, and quoted by [sars-cov-2-variants/lineage-proposals/issues/526](https://github.com/sars-cov-2-variants/lineage-proposals/issues/526) on 11 Nov. @FedeGueli

Sorry i dont get what are you responding to, what happened? i for sure mistook the issue if i ve credited soemone else.

**Comment by FedeGueli** [comment]
AH ok i see . i misunderstood the tracklist.

**Comment by Walde1nsamkeit** [comment]
Fujian/FCDC-ND2157/2023|EPI_ISL_18523045|2023-10-22 EG.5.1.8+K356T

**Comment by Walde1nsamkeit** [comment]
Singapore/R85MR218/2023|EPI_ISL_18544623|2023-11-18 from Japan
C27507Arev, T29555Crev, T29625Crev
Potential recombined with other Orf9b:I5T lineages like XBB.1.9.1* or XBB.1.22*

**Comment by Walde1nsamkeit** [comment]
USA/NJ-CDC-QDX88030603/2023|EPI_ISL_18602256|2023-11-20
FL.2.3+S:F456L / EG.5.1.1
FL.2.3> T22928C> T14679C
EG.5.1.1> C12053T> C503T, A8116G> C18175T, G22927T> C7732T> G27962A> T26310C> T27713C
Brpt: 22930\~25572
C7303T, C9430T, T15069C, C21459T, C21767T, A22005C, C23029T, C25066T, C27893T, C27942T are private

**Comment by Walde1nsamkeit** [comment]
Hong_Kong/HKU-231211-039/2023|EPI_ISL_18604522|2023-01-31 BA.2.2 Saltation
H519Y, P621S on S494P> T470N> R346T> A222V branch (Potential single patient)

**Comment by Walde1nsamkeit** [comment]
Russia/SPE-RII-MH150849S/2023|EPI_ISL_18638833|2023-11-13 HK.3.2/XBB.1.16*
