### ISSUE TITLE
XBC.1.6全球流行情况（XBC.1.6 Global prevalence）

### ISSUE THREAD

**Issue by Outpfmance** [Memorablea/COVID-19-#29]
XBC.1.6作为DeltaCron（XBC\*）家族中最顶尖的存在，在澳大利亚传播广泛，主要在南澳大利亚占绝对优势并击败各种XBB\*系列变异株，目前XBB\*还未诞生能完全推翻XBC.1.6\*的毒株，作为一款Delta与Omicron的重组毒株，它的毒性也让人捉摸不透，从现有数据来看，XBC.1.6的毒性无疑是增强了的，不过增强原理并不清楚，这更证明了这是一个值得关注的变种

XBC.1.6, as the top of the DeltaCron (XBC*) family, has been widely spread in Australia, dominated in South Australia and defeated various XBB series mutant strains. At present, XBB has not been born that can fully promote XBC.1.6* strain, which is a recombinant strain of Delta and Omicron. Its toxicity is also unclear. From the available data, the toxicity of XBC.1.6 is undoubtedly increased, but the mechanism of enhancement is not clear, which further proves that this is a noteworthy variant

**Comment by Outpfmance** [comment]
![IMG_0214](https://github.com/Memorablea/COVID-19-/assets/125484893/01a8efcd-b67c-4c7d-bc56-48720272ce1a)
5月4号，南澳大利亚上传

**Comment by Outpfmance** [comment]
![IMG_0230](https://github.com/Memorablea/COVID-19-/assets/125484893/cf90442f-5957-4376-a71b-7972486389ea)

**Comment by Outpfmance** [comment]
![IMG_0288](https://github.com/Memorablea/COVID-19-/assets/125484893/893660f8-2fc3-4ee3-b645-d7f7f8b53452)
5月10号，南澳大利亚上传

**Comment by Outpfmance** [comment]
![IMG_0343](https://github.com/Memorablea/COVID-19-/assets/125484893/504791b5-5c50-4b5c-8dd1-fcf0eaac5c00)
5月16日，SA共上传184条序列，其中，XBC.1.6占64条，为第一流行毒株

**Comment by Outpfmance** [comment]
![IMG_0410](https://github.com/Memorablea/COVID-19-/assets/125484893/6acdd8c2-0a11-4388-8fb8-b09b0d031956)
5月24日，SA上传182条序列，XBC*系占64条，XBC.1.6*仍为第一大流行毒株

**Comment by Over-There-Is** [comment]
在\*前添加\\可以避免被识别为斜体

**Comment by Walde1nsamkeit** [comment]
香港威尔斯亲王医院 XBC.1.6.3 疑似院感
EPI_ISL_17952721, EPI_ISL_17952756, EPI_ISL_17997301

**Comment by Walde1nsamkeit** [comment]
广州海关 XBC.1.6(3) XBC.1.6.1(2) XBC.1.6.3(1)

**Comment by Memorablea** [comment]
目前，我国存在XBC.1.6共7例，分布在广东、上海，存XBC.1.6、XBC.1.6.1/3支系，处于较低流行位置
