### ISSUE TITLE
需要关注的非Omicron系变种

### ISSUE THREAD

**Issue by Outpfmance** [Memorablea/COVID-19-#36]
【No.1 Saltation of AY.122(Delta/AY)】
![IMG_0633](https://github.com/Memorablea/COVID-19-/assets/125484893/801e8325-ffc3-4f15-936b-417102576da3)
![IMG_0580](https://github.com/Memorablea/COVID-19-/assets/125484893/fc2c27fe-0e89-4908-a879-a180d990a797)
重点突变（S蛋白）Spike_F486S,Spike_Y453F,Spike_K444N,Spike_P621S,Spike_V622A,Spike_D936H

【No.2 probably Beta/Omicron recombinant】
![IMG_0632](https://github.com/Memorablea/COVID-19-/assets/125484893/e7b1a82e-0c26-48bb-b990-b466b24256c8)

**Comment by Memorablea** [comment]
B.1.351（β）菲律宾跃迁演化
![image](https://github.com/Memorablea/COVID-19-/assets/125779492/b70a9e4d-ef82-4831-abf2-24a5f81d2814)
S突变
Spike A27S, Spike A701V, Spike D80A, **Spike D614G**, Spike D936N, Spike D1260H, **Spike E484K**, Spike F157L, Spike G181E, Spike K182N, Spike K1181N, Spike L242F, **Spike N440K**, **Spike N501Y**, **Spike P681R**, Spike V213G, Spike W152L, **Spike Y449S**, M G6S, M L16I, M L17V, N D415del, N N192Y, N P13L, N P80R, N S416del, N T205I, NS3 L108F, NS3 Q57H, NS3 S171L, NS3 T32I, NS7b C41F, NSP1 S135R, NSP3 A488T, NSP3 A890S, NSP3 A1526V, NSP3 C1071Y, NSP3 I1541V, NSP3 K977Q, NSP3 N891S, NSP3 S1375Y, NSP4 S163F, NSP4 V285L, NSP5 K90R, NSP6 F108del, NSP6 G107del, NSP6 S106del, NSP7 L56F, NSP12 L829F, NSP12 P323L
```
Nucl Mutations: | G174T, C241T, T670G, C3037T, G4181A, T4213C, G5387T, A5391G, A5648C, G5931A, C6843A, C7296T, A7340G, C9042T, G9407T, A10323G, del11288_11296, C11812A, C12008T, C14408T, C15925T, T17970C, C18129T, G21641T, A21801C, G22017T, C22033A, G22104A, A22108C, T22200G, C22286T, T22882G, A22908C, G23012A, A23063T, A23403G, C23604G, C23664T, A23764T, G24368A, A25105T, G25340C, C25487T, G25563T, C25714T, C25904T, C26250T, G26538A, C26568A, C26571G, C26801T, G27877T, C28253T, A28271C, C28311T, C28512G, T28642C, A28847T, C28887T, T29515A, del29516_29521, del29734_29759
```
