### ISSUE TITLE
关于中国疾控中心重点关注变异株的追踪

### ISSUE THREAD

**Issue by Memorablea** [Memorablea/COVID-19-#4]
- 2023年4月1日
2022年12月1日至2023年3月30日，全国共报送28468例本土病例新冠病毒基因组有效序列，均为奥密克戎变异株，共存在69个进化分支。主要流行株为BA.5.2.48（49.1%）、BF.7.14（27.3%）和DY.1（9.0%）（表4-1）。共发现本土重点关注变异株142例，其中，4例BQ.1、2例BQ.1.1、1例BQ.1.1.17、1例BQ.1.1.38、2例BQ.1.1.66、1例BQ.1.1.69、8例BQ.1.2、2例BQ.1.8、1例DT.2、1例EA.1、1例CH.1.1、1例CH.1.1.1、7例XBB.1、2例XBB.1.11.1、1例XBB.1.12、44例XBB.1.5、1例XBB.1.5.5、7例XBB.1.5.7、2例XBB.1.9、39例XBB.1.9.1、8例XBB.1.9.2、4例XBB.2.3和2例XBB.3。 

- 2023年4月8日
2022年12月1日至2023年4月6日，全国共报送29965例本土病例新冠病毒基因组有效序列，均为奥密克戎变异株，共存在75个进化分支。主要流行株为BA.5.2.48（48.8%）、BF.7.14（27.8%）和DY.1（8.8%）（表4-1）。共发现本土重点关注变异株192例，其中，4例BQ.1、3例BQ.1.1、1例BQ.1.1.13、1例BQ.1.1.17、1例BQ.1.1.38、1例BQ.1.1.53、2例BQ.1.1.66、1例BQ.1.1.69、8例BQ.1.2、2例BQ.1.8、1例DT.2、1例EA.1、1例CH.1.1、1例CH.1.1.1、12例XBB.1、2例XBB.1.11.1、1例XBB.1.12、63例XBB.1.5、1例XBB.1.5.5、7例XBB.1.5.7、3例XBB.1.9、53例XBB.1.9.1、15例XBB.1.9.2、4例XBB.2.3、1例XBB.2.4和2例XBB.3。

**Comment by Memorablea** [comment]
- 4月22日报

- 共监测到本土重点关注变异株603例，其中，4例BQ.1、4例BQ.1.1、19例BQ.1.1.13、1例BQ.1.1.17、1例BQ.1.1.18、1例BQ.1.1.35、1例BQ.1.1.38、1例BQ.1.1.46、1例BQ.1.1.53、2例BQ.1.1.66、1例BQ.1.1.69、8例BQ.1.2、1例BQ.1.23、2例BQ.1.8、2例CH.1.1、3例CH.1.1.1、1例CH.1.1.11、1例DT.2、1例EA.1、2例EG.1、3例EL.1、7例EM.1、1例EU.1.1、2例FB.1、3例FE.1、1例XBB、4例XBB.1、2例XBB.1.11.1、1例XBB.1.12、4例XBB.1.15、42例XBB.1.16、5例XBB.1.16.1、16例XBB.1.17.1、37例XBB.1.19.1、2例XBB.1.22、22例XBB.1.22.1、1例XBB.1.23、5例XBB.1.24、1例XBB.1.4、109例XBB.1.5、2例XBB.1.5.11、9例XBB.1.5.12、2例XBB.1.5.15、7例XBB.1.5.23、35例XBB.1.5.24、1例XBB.1.5.28、1例XBB.1.5.32、1例XBB.1.5.36、1例XBB.1.5.5、2例XBB.1.5.7、2例XBB.1.9、163例XBB.1.9.1、35例XBB.1.9.2、1例XBB.1.9.3、1例XBB.1.9.5、11例XBB.2.3、1例XBB.2.3.2、1例XBB.2.4和2例XBB.3。 

- 共监测到本土重点关注变异株603例，其中，4例BQ.1、4例BQ.1.1、19例BQ.1.1.13、1例BQ.1.1.17、1例BQ.1.1.18、1例BQ.1.1.35、1例BQ.1.1.38、1例BQ.1.1.46、1例BQ.1.1.53、2例BQ.1.1.66、1例BQ.1.1.69、8例BQ.1.2、1例BQ.1.23、2例BQ.1.8、2例CH.1.1、3例CH.1.1.1、1例CH.1.1.11、1例DT.2、1例EA.1、2例EG.1、3例EL.1、7例EM.1、1例EU.1.1、2例FB.1、3例FE.1、1例XBB、4例XBB.1、2例XBB.1.11.1、1例XBB.1.12、4例XBB.1.15、42例XBB.1.16、5例XBB.1.16.1、16例XBB.1.17.1、37例XBB.1.19.1、2例XBB.1.22、22例XBB.1.22.1、1例XBB.1.23、5例XBB.1.24、1例XBB.1.4、109例XBB.1.5、2例XBB.1.5.11、9例XBB.1.5.12、2例XBB.1.5.15、7例XBB.1.5.23、35例XBB.1.5.24、1例XBB.1.5.28、1例XBB.1.5.32、1例XBB.1.5.36、1例XBB.1.5.5、2例XBB.1.5.7、2例XBB.1.9、163例XBB.1.9.1、35例XBB.1.9.2、1例XBB.1.9.3、1例XBB.1.9.5、11例XBB.2.3、1例XBB.2.3.2、1例XBB.2.4和2例XBB.3。 

- EU=XBB.1.5.26

**Comment by Outpfmance** [comment]
2022年12月1日至2023年4月27日，全国共报送35089例本土病例新冠病毒基因组有效序列，均为奥密克戎变异株，涵盖134个进化分支。主要流行株为BA.5.2及其亚分支（构成比62.2%）和BF.7及其亚分支（构成比32.3%）等。其中，BA.5.2及其亚分支包括DY.2（18.8%）、DY.4（11.2%）、BA.5.2.48（10.9%）、DY.1（8.3%）、DY.3（5.3%）和BA.5.2.49（3.4%）等；BF.7及其亚分支包括BF.7.14（22.0%）、BF.7.14.1（3.6%）、BF.7.14.5（2.8%）、BF.7.14.4（2.4%）、BF.7.14.3（0.4%）和BF.7.14.2（0.4%）等（表4-1）。共监测到本土重点关注变异株1527例，其中，4例BQ.1、5例BQ.1.1、34例BQ.1.1.13、1例BQ.1.1.17、1例BQ.1.1.18、1例BQ.1.1.35、1例BQ.1.1.38、1例BQ.1.1.46、1例BQ.1.1.53、2例BQ.1.1.66、1例BQ.1.1.69、8例BQ.1.2、1例BQ.1.23、2例BQ.1.8、2例CH.1.1、6例CH.1.1.1、1例CH.1.1.11、2例CH.1.1.17、1例DT.2、1例EA.1、4例EG.1、3例EL.1、7例EM.1、1例ET.1、10例EU.1.1、3例FB.1、1例FD.2、6例FE.1、7例XBB、6例XBB.1、5例XBB.1.11.1、1例XBB.1.12、13例XBB.1.15、116例XBB.1.16、43例XBB.1.16.1、21例XBB.1.17.1、1例XBB.1.19、70例XBB.1.19.1、5例XBB.1.22、103例XBB.1.22.1、2例XBB.1.22.2、1例XBB.1.23、10例XBB.1.24、1例XBB.1.4、248例XBB.1.5、1例XBB.1.5.1、6例XBB.1.5.11、16例XBB.1.5.12、1例XBB.1.5.13、35例XBB.1.5.15、2例XBB.1.5.16、2例XBB.1.5.17、1例XBB.1.5.2、1例XBB.1.5.20、1例XBB.1.5.21、8例XBB.1.5.23、51例XBB.1.5.24、1例XBB.1.5.28、2例XBB.1.5.32、5例XBB.1.5.35、2例XBB.1.5.36、1例XBB.1.5.5、3例XBB.1.5.7、2例XBB.1.9、540例XBB.1.9.1、53例XBB.1.9.2、1例XBB.1.9.3、1例XBB.1.9.5、23例XBB.2.3、1例XBB.2.3.2、1例XBB.2.4、2例XBB.3。

**Comment by Over-There-Is** [comment]
EG=XBB.1.9.2
EU=XBB.1.5.26
FD=XBB.1.5.15
FE=XBB.1.18.1

**Comment by Memorablea** [comment]
让我们先关闭它......

**Comment by Outpfmance** [comment]
@Memorablea 我认为应该再观察一周再做决定

**Comment by Memorablea** [comment]
是时候将他关闭了

**Comment by Memorablea** [comment]
中疾控重新恢复更新

**Comment by Memorablea** [comment]
（2023年5月） 

　　一、全国新冠病毒感染重症和死亡病例报告情况 

　　2023年5月1日-5月31日，全国31个省（自治区、直辖市）及新疆生产建设兵团报告新增重症病例2777例、死亡病例164例（其中新冠病毒感染导致呼吸功能衰竭死亡病例3例、基础疾病合并新冠病毒感染死亡病例161例）。见图1。 

　　 

　　图1 全国新冠病毒感染新增重症和死亡病例报告情况 

　　二、全国发热门诊（诊室）诊疗情况  

　　全国31个省（自治区、直辖市）及新疆生产建设兵团发热门诊（诊室）诊疗量从2023年5月1日的18.3万上升至5月16日的36.0万，之后波动下降至5月31日的29.4万。见图2。   

　　

　　图2 全国发热门诊（诊室）诊疗人数变化趋势 

　　三、哨点医院监测情况 

　　全国哨点医院流感样病例占门（急）诊就诊人数比例从2023年第17周（5月1日-5月7日）的4.6%上升至第20周（5月15日-5月21日）的6.2%，第21周（5月22日-5月28日）回落至5.8%。见图3-1。 

　　  

　　图3-1  全国哨点医院报告的流感样病例占比变化趋势 

　　流感样病例新冠病毒阳性率从第17周的8.8%快速上升至第20周的40.7%，之后缓慢上升至21周的42.5%。见图3-2。 

　　  

　　 图3-2 全国哨点医院流感样病例新冠和流感病毒阳性率变化趋势  

　　四、本土病例病毒变异监测情况 

　　2023年5月1日-5月31日，全国31个省（自治区、直辖市）及新疆生产建设兵团共报送14732例本土病例新冠病毒基因组有效序列，均为奥密克戎变异株，涵盖160个进化分支，主要流行株为XBB系列变异株，占比前三位的分别为XBB.1.9及其亚分支、XBB.1.16及其亚分支、XBB.1.5及其亚分支。 

　　根据采样日期， XBB及其亚分支的占比逐渐增加，从5月1日-5月7日的84.6%，增长到5月22日-5月28日的92.4%。见图4。 

　　  

　　图4 全国新型冠状病毒感染本土病例变异株变化趋势 

　　注：世界卫生组织5月5日宣布新冠病毒感染疫情不再构成“国际关注的突发公共卫生事件”。新冠病毒感染在我国属于 “乙类乙管”传染病，按照法定传染病疫情信息公布要求每月公布一次。 

　　综合监测数据显示，今年2月至4月上旬全国新冠病毒感染疫情局部零星散发，4月下旬开始逐步上升，5月下旬上升趋势减缓，目前呈下降趋势。与4月相比，5月发热门诊就诊量、重症和死亡病例有所增加，但总体水平较低，远低于去年年底疫情高峰时情况，重症和死亡病例以老年人群、患有基础性疾病人群为主，死亡病例平均年龄79.3岁，其中90%以上为基础性疾病合并新冠病毒感染。

**Comment by Over-There-Is** [comment]
信息量减少，参考价值大降

**Comment by Memorablea** [comment]
关闭喽，添加报告标识

> 信息量减少，参考价值大降

**Comment by Outpfmance** [comment]
不需要关闭，信息量少，但仍有参考价值，毕竟不是所有的序列都会被上传到GISAID与Genbase

**Comment by Walde1nsamkeit** [comment]
https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202307/t20230705_267605.html
阳性率15.4%，6月共上报12431条序列，XBB.1.22\*取代XBB.1.5\*成为本土第三大株系，BA.2.75\*（可能以FR.1\*为主）占比持续降低

**Comment by Memorablea** [comment]
[全国新冠感染情况7月](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202308/t20230803_268370.html)
全国报告新增重症病例455例、死亡病例65例（其中新冠病毒感染导致呼吸功能衰竭死亡病例0例、基础疾病合并新冠病毒感染死亡病例65例）。新冠病毒阳性率从第21周(5月22日-5月28日）的42.5%持续下降，第28周（7月10日-7月16日）下降至12.0%后开始略有上升，第30周（7月24日-7月30日）上升至13.4%。
