### ISSUE TITLE
讨论是否创建猴痘

### ISSUE THREAD

**Issue by Memorablea** [Memorablea/COVID-19-#44]

**Comment by Memorablea** [comment]
@Outpfmance @Over-There-Is  你们的意见？

**Comment by Outpfmance** [comment]
@Memorablea 我并不认为需要这样一个议题，首先，猴痘的传播目前十分有限，无法真正形成有威胁的大规模传播，国内放松入境政策后出现输入是很正常的事情；其次，这是一个关于COVID-19的专门话题，猴痘属于另一种传染病，不应该进入这里混淆。最后，关于国内外猴痘流通情况及变异我会保持监测，有新情况我会及时发出预警

**Comment by Memorablea** [comment]
OK
