### ISSUE TITLE
GISAID CHINA REPORT[202308] 

### ISSUE THREAD

**Issue by Memorablea** [Memorablea/COVID-19-#47]

**Comment by Walde1nsamkeit** [comment]
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2c58f_9add90.json?f_userOrOld=uploaded%20sample
![2023-08-14 (4)](https://github.com/Memorablea/COVID-19-/assets/38100637/a7eaa2de-1734-4d34-a3fd-c737a8b8a558)
![2023-08-14 (5)](https://github.com/Memorablea/COVID-19-/assets/38100637/b3b470ca-7aab-46b8-9b75-bb10cec2cdbc)

**Comment by Memorablea** [comment]
Shutdown due to unmanned maintenance
